# list of datasources to insert/update depending
datasources:
  # ref: https://github.com/vegasbrianc/prometheus/blob/master/grafana/provisioning/datasources/datasource.yml
- name: Prometheus
  type: prometheus
  access: proxy
  url: http://prometheus:9090
  isDefault: true
  basicAuth: false
  jsonData:
     graphiteVersion: "1.1"
     tlsAuth: false
     tlsAuthWithCACert: false
  secureJsonData:
    tlsCACert: ""
    tlsClientCert: ""
    tlsClientKey: ""
  version: 1
  editable: true

