package pocket

import "fmt"

type Chain struct {
	ID           string
	Name         string
	PortalPrefix string
	IsMonetized  bool
}

func ChainFromID(id string) (Chain, error) {
	chain, ok := allChains[id]
	if !ok {
		return Chain{}, fmt.Errorf("ChainFromID: unknown chain %s", id)
	}

	return chain, nil
}

var allChains = map[string]Chain{
	"0054": {
		ID:           "0054",
		Name:         "Osmosis Mainnet",
		PortalPrefix: "osmosis-mainnet",
		IsMonetized:  true,
	},
	"0060": {
		ID:           "0060",
		Name:         "Starknet Mainnet",
		PortalPrefix: "starknet-mainnet",
		IsMonetized:  true,
	},
	"0061": {
		ID:           "0061",
		Name:         "Starknet Testnet",
		PortalPrefix: "starknet-testnet",
		IsMonetized:  true,
	},
	"0066": {
		ID:           "0066",
		Name:         "Arbitrum One",
		PortalPrefix: "arbitrum-one",
		IsMonetized:  true,
	},
	"0067": {
		ID:           "0067",
		Name:         "Velas Mainnet",
		PortalPrefix: "velas-mainnet",
		IsMonetized:  true,
	},
	"0068": {
		ID:           "0068",
		Name:         "Velas Mainnet Archival",
		PortalPrefix: "velas-mainnet-archival",
		IsMonetized:  true,
	},
	"A087": {
		ID:           "A087",
		Name:         "Optimism Sepolia Archival",
		PortalPrefix: "optimism-sepolia-archival",
		IsMonetized:  true,
	},
	"A086": {
		ID:           "A086",
		Name:         "Arbitrum Sepolia Archival",
		PortalPrefix: "arbitrum-sepolia-archival",
		IsMonetized:  true,
	},
	"A085": {
		ID:           "A085",
		Name:         "Polygon Amoy Testnet Archival",
		PortalPrefix: "amoy-testnet-archival",
		IsMonetized:  true,
	},
	"0029": {
		ID:           "0029",
		Name:         "Algorand",
		PortalPrefix: "algorand-mainnet",
		IsMonetized:  true,
	},
	"000D": {
		ID:           "000D",
		Name:         "Algorand Archival",
		PortalPrefix: "algorand-archival",
		IsMonetized:  false,
	},
	"0045": {
		ID:           "0045",
		Name:         "Algorand Testnet",
		PortalPrefix: "algorand-testnet",
		IsMonetized:  false,
	},
	"0A45": {
		ID:           "0A45",
		Name:         "Algorand TestNet Archival",
		PortalPrefix: "algorand-testnet-archival",
		IsMonetized:  false,
	},
	"0030": {
		ID:           "0030",
		Name:         "Arweave",
		PortalPrefix: "arweave-mainnet",
		IsMonetized:  false,
	},
	"0003": {
		ID:           "0003",
		Name:         "Avalanche",
		PortalPrefix: "avax-archival",
		IsMonetized:  true,
	},
	"00A3": {
		ID:           "00A3",
		Name:         "Avalanche Archival",
		PortalPrefix: "avax-archival",
		IsMonetized:  true,
	},
	"03CB": {
		ID:           "03CB",
		Name:         "Swimmer Mainnet",
		PortalPrefix: "avax-cra",
		IsMonetized:  true,
	},
	"000E": {
		ID:           "000E",
		Name:         "Avalanche Fuji",
		PortalPrefix: "avax-fuji",
		IsMonetized:  false,
	},
	"0004": {
		ID:           "0004",
		Name:         "Binance Smart Chain",
		PortalPrefix: "bsc-mainnet",
		IsMonetized:  true,
	},
	"0010": {
		ID:           "0010",
		Name:         "Binance Smart Chain (Archival)",
		PortalPrefix: "bsc-archival",
		IsMonetized:  true,
	},
	"A089": {
		ID:           "A089",
		Name:         "BNB Archival (OP)",
		PortalPrefix: "op-bnb-archival",
		IsMonetized:  true,
	},
	"A0CA": {
		ID:           "A0CA",
		Name:         "Celestia DA Archival",
		PortalPrefix: "celestia-da-archival",
		IsMonetized:  true,
	},
	"A0CB": {
		ID:           "A0CB",
		Name:         "Celestia Consensus Archival",
		PortalPrefix: "celestia-consensus-archival",
		IsMonetized:  true,
	},
	"A0CC": {
		ID:           "A0CC",
		Name:         "Celestia Testnet DA Archival",
		PortalPrefix: "celestia-testnet-da-archival",
		IsMonetized:  true,
	},
	"A0CD": {
		ID:           "A0CD",
		Name:         "Celestia Testnet Consensus Archival",
		PortalPrefix: "celestia-testnet-consensus-archival",
		IsMonetized:  true,
	},
	"0065": {
		ID:           "0065",
		Name:         "Celo Mainnet",
		PortalPrefix: "celo-mainnet",
		IsMonetized:  true,
	},
	"A090": {
		ID:           "A090",
		Name:         "Blast Archival",
		PortalPrefix: "blast-archival",
		IsMonetized:  true,
	},
	"0011": {
		ID:           "0011",
		Name:         "Binance Smart Chain Testnet",
		PortalPrefix: "bsc-testnet",
		IsMonetized:  false,
	},
	"0012": {
		ID:           "0012",
		Name:         "Binance Smart Chain Testnet Archival",
		PortalPrefix: "bsc-testnet-archival",
		IsMonetized:  false,
	},
	"0002": {
		ID:           "0002",
		Name:         "Bitcoin",
		PortalPrefix: "btc-mainnet",
		IsMonetized:  false,
	},
	"0074": {
		ID:           "0074",
		Name:         "Polygon zkEVM Mainnet",
		PortalPrefix: "polygon-zkevm-mainnet",
		IsMonetized:  false,
	},
	"0076": {
		ID:           "0076",
		Name:         "Sui Mainnet",
		PortalPrefix: "sui-mainnet",
		IsMonetized:  false,
	},
	"0079": {
		ID:           "0079",
		Name:         "Base Mainnet",
		PortalPrefix: "base-fullnode-mainnet",
		IsMonetized:  false,
	},
	"0080": {
		ID:           "0080",
		Name:         "Base Testnet",
		PortalPrefix: "base-fullnode-testnet",
		IsMonetized:  false,
	},
	"0084": {
		ID:           "0084",
		Name:         "zkSync Era",
		PortalPrefix: "zksync-era",
		IsMonetized:  false,
	},
	"0048": {
		ID:           "0048",
		Name:         "BOBA Mainnet",
		PortalPrefix: "boba-mainnet",
		IsMonetized:  true,
	},
	"03DF": {
		ID:           "03DF",
		Name:         "DFKchain Subnet",
		PortalPrefix: "avax-dfk",
		IsMonetized:  true,
	},
	"0021": {
		ID:           "0021",
		Name:         "Ethereum Mainnet",
		PortalPrefix: "eth-mainnet",
		IsMonetized:  true,
	},
	"0022": {
		ID:           "0022",
		Name:         "Ethereum Mainnet Archival",
		PortalPrefix: "eth-archival",
		IsMonetized:  true,
	},
	"0028": {
		ID:           "0028",
		Name:         "Ethereum Archival Trace",
		PortalPrefix: "eth-archival-trace",
		IsMonetized:  true,
	},
	"0062": {
		ID:           "0062",
		Name:         "Ethereum Mainnet High Gas",
		PortalPrefix: "ethereum-mainnet-high-gas",
		IsMonetized:  true,
	},
	"0026": {
		ID:           "0026",
		Name:         "Ethereum Goerli",
		PortalPrefix: "eth-goerli",
		IsMonetized:  true,
	},
	"0063": {
		ID:           "0063",
		Name:         "Ethereum Goerli Archival",
		PortalPrefix: "goerli-archival",
		IsMonetized:  true,
	},
	"0024": {
		ID:           "0024",
		Name:         "Ethereum Kovan",
		PortalPrefix: "poa-kovan",
		IsMonetized:  true,
	},
	"0025": {
		ID:           "0025",
		Name:         "Ethereum Rinkeby",
		PortalPrefix: "eth-rinkeby",
		IsMonetized:  true,
	},
	"0023": {
		ID:           "0023",
		Name:         "Ethereum Ropsten",
		PortalPrefix: "eth-ropsten",
		IsMonetized:  true,
	},
	"0046": {
		ID:           "0046",
		Name:         "Evmos Mainnet",
		PortalPrefix: "evmos-mainnet",
		IsMonetized:  false,
	},
	"BE2A": {
		ID:           "BE2A",
		Name:         "Experimental",
		PortalPrefix: "",
		IsMonetized:  false,
	},
	"0049": {
		ID:           "0049",
		Name:         "Fantom",
		PortalPrefix: "fantom-mainnet",
		IsMonetized:  true,
	},
	"A088": {
		ID:           "A088",
		Name:         "Frax Archival",
		PortalPrefix: "frax-archival",
		IsMonetized:  true,
	},
	"0005": {
		ID:           "0005",
		Name:         "FUSE",
		PortalPrefix: "fuse-mainnet",
		IsMonetized:  true,
	},
	"000A": {
		ID:           "000A",
		Name:         "FUSE Archival",
		PortalPrefix: "fuse-archival",
		IsMonetized:  true,
	},
	"0027": {
		ID:           "0027",
		Name:         "Gnosis Chain",
		PortalPrefix: "gnosischain-mainnet",
		IsMonetized:  true,
	},
	"000C": {
		ID:           "000C",
		Name:         "Gnosis Chain Archival",
		PortalPrefix: "gnosischain-archival",
		IsMonetized:  true,
	},
	"0040": {
		ID:           "0040",
		Name:         "Harmony Shard 0",
		PortalPrefix: "harmony-0",
		IsMonetized:  true,
	},
	"B081": {
		ID:           "B081",
		Name:         "Holesky Beacon",
		PortalPrefix: "holesky-beacon",
		IsMonetized:  true,
	},
	"0081": {
		ID:           "0081",
		Name:         "Holesky Testnet",
		PortalPrefix: "holesky-fullnode-testnet",
		IsMonetized:  true,
	},
	"0082": {
		ID:           "0082",
		Name:         "Scroll Mainnet",
		PortalPrefix: "scroll-fullnode-mainnet",
		IsMonetized:  true,
	},
	"0083": {
		ID:           "0083",
		Name:         "Radix Mainnet",
		PortalPrefix: "radix-mainnet",
		IsMonetized:  true,
	},
	"0A40": {
		ID:           "0A40",
		Name:         "Harmony Shard 0 Archival",
		PortalPrefix: "harmony-0-archival",
		IsMonetized:  false,
	},
	"0041": {
		ID:           "0041",
		Name:         "Harmony Shard 1",
		PortalPrefix: "harmony-1",
		IsMonetized:  false,
	},
	"0A41": {
		ID:           "0A41",
		Name:         "Harmony Shard 1 Archival",
		PortalPrefix: "harmony-1-archival",
		IsMonetized:  false,
	},
	"0042": {
		ID:           "0042",
		Name:         "Harmony Shard 2",
		PortalPrefix: "harmony-2",
		IsMonetized:  false,
	},
	"0A42": {
		ID:           "0A42",
		Name:         "Harmony Shard 2 Archival",
		PortalPrefix: "harmony-2-archival",
		IsMonetized:  false,
	},
	"0043": {
		ID:           "0043",
		Name:         "Harmony Shard 3",
		PortalPrefix: "harmony-3",
		IsMonetized:  false,
	},
	"0A43": {
		ID:           "0A43",
		Name:         "Harmony Shard 3 Archival",
		PortalPrefix: "harmony-3-archival",
		IsMonetized:  false,
	},
	"0044": {
		ID:           "0044",
		Name:         "IoTeX",
		PortalPrefix: "iotex-mainnet",
		IsMonetized:  true,
	},
	"0069": {
		ID:           "0069",
		Name:         "Oasys Mainnet Archival",
		PortalPrefix: "oasys-mainnet-archival",
		IsMonetized:  true,
	},
	"0070": {
		ID:           "0070",
		Name:         "Oasys Mainnet",
		PortalPrefix: "oasys-mainnet",
		IsMonetized:  true,
	},
	"0071": {
		ID:           "0071",
		Name:         "Kava Mainnet",
		PortalPrefix: "kava-mainnet",
		IsMonetized:  true,
	},
	"0072": {
		ID:           "0072",
		Name:         "Kava Mainnet Archival",
		PortalPrefix: "kava-mainnet-archival",
		IsMonetized:  true,
	},
	"0075": {
		ID:           "0075",
		Name:         "Scroll Testnet",
		PortalPrefix: "scroll-testnet",
		IsMonetized:  true,
	},
	"0077": {
		ID:           "0075",
		Name:         "Sepolia Testnet",
		PortalPrefix: "sepolia-testnet",
		IsMonetized:  true,
	},
	"0078": {
		ID:           "0078",
		Name:         "Sepolia Archival",
		PortalPrefix: "sepolia-archival",
		IsMonetized:  true,
	},
	"0052": {
		ID:           "0052",
		Name:         "NEAR",
		PortalPrefix: "near-mainnet",
		IsMonetized:  true,
	},
	"0053": {
		ID:           "0053",
		Name:         "Optimism",
		PortalPrefix: "optimism-mainnet",
		IsMonetized:  true,
	},
	"A053": {
		ID:           "A053",
		Name:         "Optimism Archival",
		PortalPrefix: "optimism-archival",
		IsMonetized:  true,
	},
	"0056": {
		ID:           "0056",
		Name:         "Klaytn Mainnet",
		PortalPrefix: "klaytn-mainnet",
		IsMonetized:  true,
	},
	"0057": {
		ID:           "0057",
		Name:         "Meter Mainnet",
		PortalPrefix: "meter-mainnet",
		IsMonetized:  true,
	},
	"0058": {
		ID:           "0058",
		Name:         "Metis Mainnet",
		PortalPrefix: "metis-mainnet",
		IsMonetized:  true,
	},
	"0059": {
		ID:           "0059",
		Name:         "Dogechain Mainnet",
		PortalPrefix: "dogechain-mainnet",
		IsMonetized:  true,
	},
	"0047": {
		ID:           "0047",
		Name:         "OKC Mainnet",
		PortalPrefix: "oKc-mainnet",
		IsMonetized:  true,
	},
	"0001": {
		ID:           "0001",
		Name:         "Pocket Network",
		PortalPrefix: "mainnet",
		IsMonetized:  true,
	},
	"A001": {
		ID:           "0001",
		Name:         "Pocket Network Archival",
		PortalPrefix: "pokt-archival",
		IsMonetized:  true,
	},
	"0009": {
		ID:           "0009",
		Name:         "Polygon Matic",
		PortalPrefix: "poly-mainnet",
		IsMonetized:  true,
	},
	"000B": {
		ID:           "000B",
		Name:         "Polygon Archival",
		PortalPrefix: "poly-archival",
		IsMonetized:  true,
	},
	"B021": {
		ID:           "B021",
		Name:         "Ethereum Beacon",
		PortalPrefix: "eth-beacon",
		IsMonetized:  true,
	},
	"000F": {
		ID:           "000F",
		Name:         "Polygon Mumbai",
		PortalPrefix: "poly-mumbai",
		IsMonetized:  false,
	},
	"00AF": {
		ID:           "00AF",
		Name:         "Polygon Mumbai Archival",
		PortalPrefix: "poly-mumbai-archival",
		IsMonetized:  false,
	},
	"0006": {
		ID:           "0006",
		Name:         "Solana",
		PortalPrefix: "sol-mainnet",
		IsMonetized:  true,
	},
	"C006": {
		ID:           "C006",
		Name:         "Solana Custom",
		PortalPrefix: "sol-mainnet-custom",
		IsMonetized:  true,
	},
	"0031": {
		ID:           "0031",
		Name:         "Solana Testnet",
		PortalPrefix: "sol-testnet",
		IsMonetized:  false,
	},
	"0050": {
		ID:           "0050",
		Name:         "Moonbeam",
		PortalPrefix: "moonbeam-mainnet",
		IsMonetized:  true,
	},
	"0051": {
		ID:           "0050",
		Name:         "Moonriver",
		PortalPrefix: "moonriver-mainnet",
		IsMonetized:  true,
	},
	"7A00": {
		ID:           "7A00",
		Name:         "Taiko Mainnet",
		PortalPrefix: "",
		IsMonetized:  true,
	},
	"7A10": {
		ID:           "7A10",
		Name:         "Taiko Testnet",
		PortalPrefix: "",
		IsMonetized:  true,
	},
}
